### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/reporting-engine#167]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] base_report_assembler
- [x] bi_view_editor - By @astirpe - #202 
- [x] bi_sql_editor - By @hveficent - #230
- [ ] report_py3o - ~~By @BT-nfrei - #217~~ - By @tbaden - #285
- [ ] report_qweb_element_page_visibility - By @svazquezco - #186 
- [x] report_qweb_parameter - By @etobella - #169 
- [x] report_qweb_pdf_watermark - By @schout-it - #236 
- [ ] report_qweb_signer
- [x] report_wkhtmltopdf_param - #182 
- [x] report_xlsx - By @etobella - #171 
- [x] report_xlsx_helper - By @luc-demeyer - #243
- [x] report_xml - By @etobella - #168

**Comment by gabrielcardoso21** [comment]
I'm working in the migration of report_xlsx

**Comment by pedrobaeza** [comment]
Thanks, noted.

**Comment by ghost** [comment]
Hi!
I'm starting to work in report_qweb_element_page_visibility migration. Should I open an issue? or Can I do a pull directly?

**Comment by pedrobaeza** [comment]
@svazquezco noted in the main comment

**Comment by ghost** [comment]
Hello,
The module bi_view_editor is going to be migrated?
Thanks!

**Comment by jr1003** [comment]
hi.. o/ .. py3o is going to be migrated????.. i can help?

**Comment by pedrobaeza** [comment]
Go ahead then. Make a PR with the migration following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by bjr-htb** [comment]
Could you please tell me the news about report_qweb_pdf_watermark?
When will be migrated to 11.0 verison?

**Comment by pedrobaeza** [comment]
There's no date, as these contributions are voluntary. If you want to speed up the migration, you can migrate it yourself, or pay someone to do it.

**Comment by BT-nfrei** [comment]
Hello everyone,
I created the PR #217 for the migration of py3o. So if you would like to contribute, please join the discussion on PR #217.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza 
report_wkhtmltopdf_param #182 is done

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, add to the list bi_sql_editor - By @hveficent - #230 that is already migrated and merged

Please, add to the list report_xlsx_helper - By @luc-demeyer - #243 that is already migrated and merged

**Comment by emagdalenaC2i** [comment]
report_py3o - By @BT-nfrei - #217 is closed and superseed - By @tbaden - #285
