### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/reporting-engine#27]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] ~~report_xls~~ (Deprecated) - By @mreficent - #151 
- [x] report_custom_filename - By @susport - #82 
- [ ] base_report_assembler
- [x] report_qweb_element_page_visibility - By @alnslang - #54
- [ ] report_qweb_signer
- [ ] report_xml
- [ ] report_xml_sample

**Comment by sdu-odoo** [comment]
when i install and run moduel at time it will give me an error like 

 (u"Unknown report type: xlsx: (<type 'exceptions.NotImplementedError'>, NotImplementedError(u'Unknown report type: xlsx',), <traceback object at 0x7f1c1816f878>)", None)

for that i create only xml file for action 

<?xml version="1.0" encoding="utf-8"?>
<odoo>

<report 
        id="partner_xlsx"
        model="res.partner"
        string="Print to XLSX"
        report_type="xlsx"
        name="res.partner.xlsx"
        file="res.partner.xlsx"
        attachment_use="False"
    />
    </odoo>

**Comment by pedrobaeza** [comment]
@sdu-odoo, don't report here issues, but in independent ones. I delete your comment and mine right now.

**Comment by SodexisTeam** [comment]
For info, we are migrating report_qweb_element_page_visibility.

**Comment by AaronHForgeFlow** [comment]
is the report_xls module be ported to v9? We are migrating mrp_bom_structure_xls to v9.

**Comment by pedrobaeza** [comment]
The idea is to use now report_xlsx. You can adapt your module to be mrp_bom_structure_xlsx, or migrate report_xls.
