### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/reporting-engine#653]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] base_comment_template - By @AMhadhbi - #664
- [ ] bi_sql_editor - By @legalsylvain - #670
- [x] report_py3o - By @alexis-via - #695
- [ ] report_qr
- [x] report_qweb_encrypt - By @payen000 - #779
- [ ] report_qweb_parameter
- [x] report_qweb_pdf_watermark - By @bvanjeelharia - #734
- [ ] report_wkhtmltopdf_param
- [x] report_xlsx - By @RodrigoBM - #690
- [x] report_xlsx_helper - By @RodrigoBM - #655
- [x] report_xml - By @Du-ma - #663
- [ ] sql_export - By @legalsylvain - #671
- [ ] sql_export_excel
- [ ] sql_export_mail - By @legalsylvain - #672
- [ ] sql_request_abstract - By @legalsylvain - #669

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by RodrigoBM** [comment]
PR report_xlsx_helper https://github.com/OCA/reporting-engine/pull/655

**Comment by Du-ma** [comment]
Working on `report_xml`, should have a PR ready tomorrow.

**Comment by Du-ma** [comment]
`report_xml` #663

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working on `report_qweb_parameter` #667

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working on `report_qr` #673

**Comment by RodrigoBM** [comment]
it is possible to merge [report_xlsx](https://github.com/OCA/reporting-engine/pull/654), it has two Reviewers Thanks

**Comment by michaelwittwer** [comment]
Any chance to add the module `report_py3o` to the list? Unfortunately I can not contribute to the migration since I am only a user of the module. Thanks for all the hard work.

**Comment by pedroguirao** [comment]
Hi all, some one working on : report_qweb_pdf_watermark?

**Comment by RodrigoBM** [comment]
report_xlsx: https://github.com/OCA/reporting-engine/pull/690 pr alternative to the original pr https://github.com/OCA/reporting-engine/pull/654

**Comment by matiasperalta1** [comment]
report_substitution https://github.com/OCA/reporting-engine/pull/700

**Comment by ferran-S73** [comment]
report_qweb_element_page_visibility https://github.com/OCA/reporting-engine/pull/704

**Comment by legalsylvain** [comment]
report_label : https://github.com/OCA/reporting-engine/pull/708

**Comment by AnizR** [comment]
report_csv: #682 Is it possible to merge it, it has some reviews?

**Comment by AurelijaNorvaisaite** [comment]
@alexis-via is this PR still active? #695

**Comment by rbellanova** [comment]
Hello! `kpi_dashboard` porting will be considered?

**Comment by pedrobaeza** [comment]
It doesn't have too much sense now that `spreadsheet_oca` is present.
