### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/reporting-engine#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] base_report_assembler
- [x] bi_view_editor - By @astirpe - #106
- [x] ~~report_custom_filename~~ - Removed by @mourad-ehm in #116, feature now in Odoo
- [x] report_py3o - By @alexis-via - #78 
- [x] report_qweb_element_page_visibility - By @invitu - #94 
- [x] report_qweb_pdf_watermark - By @stefanrijnhart - #126
- [x] report_qweb_signer - By @pedrobaeza - #145
- [x] report_xml - By @etobella - #143 
- [x] ~~report_xls~~ (Deprecated) - By @mreficent - #152
- [x] report_xlsx - By @adrienpeiffer - #76

**Comment by pedrobaeza** [comment]
@sbidoul should we remove old report_xls module from this repo branch?

**Comment by sbidoul** [comment]
@pedrobaeza I'd leave it here for now. The main usage for that module was afr_xls, which have been rewritten. But there maybe others (eg account_asset_management_xlsx). cc/ @luc-demeyer

**Comment by luc-demeyer** [comment]
Leave report_xls in the repo for the time being.
The first V9 and V10 versions of account_asset_management_xls will be based on the ported version of report_xls (this work is in progress). In a second phase I'll migrate the asset mgt reporting module (and other ones using the report_xls templates) to an enhanced report_xlsxs (or an add-on module to report_xlsx supporting templates), allowing us to deprecate at that point in time report_xls.
